const Map<String, String> appStringsEn = {
  'appName': 'AntiList',
  'appTagline': 'A list of what you will not do',
  'loading': 'Loading…',
  'shop': 'Shop',
  'settings': 'Settings',
  'dashboard': 'Today',
  'navDash': 'Today',
  'navLog': 'Log',
  'navInsights': 'Insights',
  'navMore': 'More',
  'notToDo': 'NOT TO DO',
  'notToDoSub': 'Focus on what you choose to stop.',
  'triggerLog': 'TRIGGER LOG',
  'triggerLogSub': 'Awareness breaks the loop.',
  'insights': 'INSIGHTS',
  'insightsSub': 'Proof you’re rewiring. Keep going.',
  'avoidStreak': 'AVOIDANCE STREAK',
  'days': '{n} DAYS',
  'rescueTitle': 'RESCUE BUTTON',
  'rescueSub': 'Urge hit hard? Reset in 90 seconds.',
  'rescueRide': 'Ride the urge. Do nothing else.',
  'rescueDone': 'Urge passed. You held the line.',
  'rescueAbort': 'Still spinning — log it instead',
  'heldToday': 'Held',
  'markHeld': 'I didn’t do this',
  'logUrge': 'Log urge',
  'filterAll': 'ALL',
  'situation': 'Situation',
  'urge': 'Urge',
  'replacement': 'Replacement',
  'whatHappened': 'What happened',
  'totalReplacement': 'TOTAL REPLACEMENT TIME',
  'timeReclaimed': 'Time reclaimed',
  'moneySaved': 'Money saved',
  'urgesResisted': 'Urges resisted',
  'triggerHeatmap': 'Trigger heatmap',
  'topReplacements': 'Top replacements',
  'relapseNotes': 'Relapse notes',
  'relapseHint': 'What was tough this week?',
  'resetWeek': 'RESET WEEK',
  'addLog': 'Log a trigger',
  'save': 'Save',
  'cancel': 'Cancel',
  'urgeLevel': 'Urge 1–10',
  'outcomePassed': 'Urge passed',
  'outcomeBetter': 'Felt better',
  'outcomeSlipped': 'Slipped, logged',
  'minutesShort': '{n}m',
  'lockedHabit': 'Unlock extra habits in Shop',
  'emptyLog': 'No triggers logged yet. When an urge hits, rescue or log it.',
  'emptyReplace': 'No replacements yet.',

  'shopTagline': 'Looks and extras for the hold',
  'shopDailyHarvest': 'Daily seals',
  'shopNowGrowing': 'Now active',
  'shopSeedRack': 'Looks',
  'shopPlotBeds': 'Backdrops',
  'shopCardStyles': 'Card styles',
  'shopToolshed': 'Tools',
  'shopVipBadge': 'PRO',
  'shopCatalog': 'Shop',
  'shopMore': 'More',
  'shopPacks': 'Coin packs',
  'shopToday': 'Today',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuBackgrounds': 'Backgrounds',
  'shopMenuSkins': 'Styles',
  'shopMenuFeatures': 'Features',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Hide coin prompts on Today.',
  'shopThemeDefault': 'Blackout',
  'shopThemeDefaultDesc': 'Rescue red on true black',
  'shopBgDefault': 'Void',
  'shopBgDefaultDesc': 'Quiet dark ground',
  'shopSkinDefault': 'Parchment',
  'shopSkinDefaultDesc': 'Off-white not-to-do cards',
  'shopThemeEmerald': 'Voltage',
  'shopThemeEmeraldDesc': 'Electric blue on night',
  'shopThemeGold': 'Signal',
  'shopThemeGoldDesc': 'Caution yellow, black ground',
  'shopThemeMidnight': 'After hours',
  'shopThemeMidnightDesc': 'Indigo night, lilac spark',
  'shopBgForest': 'Red room',
  'shopBgForestDesc': 'Soft crimson haze',
  'shopBgAurora': 'Night desk',
  'shopBgAuroraDesc': 'Deep evening work',
  'shopBgSunset': 'Amber hour',
  'shopBgSunsetDesc': 'Warm dusk hold',
  'shopSkinSoft': 'Frost card',
  'shopSkinSoftDesc': 'Soft glass on every card',
  'shopSkinNeon': 'Glow hold',
  'shopSkinNeonDesc': 'A glow around the list cards',
  'shopFeatDoubleCoins': 'Double coins',
  'shopFeatDoubleCoinsDesc': 'Earn 2× from daily seals',
  'shopFeatImperial': 'Replacement pack',
  'shopFeatImperialDesc': 'More swaps when an urge hits',
  'shopFeatJobs': 'Extra habits',
  'shopFeatJobsDesc': 'Unlock staying up, sugar, toxic scroll',

  'buy': 'Unlock',
  'owned': 'Owned',
  'equipped': 'Active',
  'equip': 'Use',
  'resetDefault': 'Use blackout',
  'resetDefaultDesc': 'Default red, void, parchment cards',
  'lookResetDone': 'Back to blackout',
  'currentLook': 'Look',
  'purchaseSuccess': 'Unlocked in AntiList',
  'purchaseFailed': 'Purchase failed. Try again.',
  'coinsAdded': 'Coins added',
  'coinsAddedWithBonus': 'Coins added — bonus included',
  'removeAdsUnlocked': 'Ads removed',
  'dailyReward': 'Daily reward',
  'dailyClaimed': 'Claimed',
  'claimDaily': 'Claim',
  'loginStreak': '{days}-day streak',
  'spinWheel': 'Lucky seal',
  'spinNow': 'Spin',
  'spinUsed': 'Come back tomorrow',
  'earnCoins': 'Daily seals',
  'earnCoinsDesc': 'Claim the day, spin, or buy a pack',
  'buyCoins': 'Buy coin packs',
  'buyCoinsDesc': 'Instant coins via Google Play',
  'promoBuyShort': 'Buy',
  'levelRewardEarned': 'Hold stars',
  'dailyRewardClaimed': 'Daily reward claimed',
  'spinRewardEarned': 'Spin reward earned',
  'promoTitle': 'Need more coins?',
  'promoSubtitle': 'Packs unlock looks and extras',
  'promoBuy': 'Buy coins',
  'restorePurchases': 'Restore purchases',
  'billingUnavailable': 'Billing unavailable',
  'insufficientCoins': 'Not enough coins',
  'alreadyOwned': 'Already owned',
  'applied': 'Applied',
  'apply': 'Apply',
  'active': 'Active',
  'unlocked': 'Unlocked',
  'useDefault': 'Default',
  'appearance': 'Appearance',
  'darkMode': 'Dark mode',
  'about': 'About',
  'version': 'Version {v}',
  'privacyPolicy': 'Privacy policy',
  'privacyPolicyTitle': 'Privacy Policy – AntiList',
  'privacyPolicyBody':
      'AntiList stores your not-to-do list, trigger logs, replacement times, coins, and shop looks on this device. We do not ask for an account, microphone, or location. Purchases go through the store. The remote config only checks whether billing should stay on.',
  'onboardTitle1': 'Stop, don’t stack',
  'onboardDesc1': 'A reverse to-do: the only list that matters is what you refuse today.',
  'onboardTitle2': 'Name the trigger',
  'onboardDesc2': 'Log situation, urge, and a swap. Awareness breaks the loop.',
  'onboardTitle3': '90-second rescue',
  'onboardDesc3': 'When the urge hits, ride 90 seconds. Then see time and money you kept.',
  'skipOnboard': 'Skip',
  'next': 'Next',
  'getStarted': 'Start holding',
  'jobsThisWeek': '{n} habits on the list',
};
